root: true
env:
  es2020: true
  node: true
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelOptions:
    babelrc: false
    configFile: false
    presets: ['@babel/preset-env']
extends:
  - '@thnetii/node-base'
