on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  filesync-gitignore:
    runs-on: ubuntu-latest
    steps:
      - id: get-workflow-id
        uses: thnetii/.github/actions/get-workflow-id@main
      - id: checkout-source1
        name: Checkout github/gitignore to './source1'
        uses: actions/checkout@v3
        with:
          repository: github/gitignore
          path: source1
      - id: checkout-source2
        name: Checkout thnetii/.github to './source2'
        uses: actions/checkout@v3
        with:
          repository: thnetii/.github
          path: source2
      - id: checkout-target
        name: Checkout ${{ github.repository }}@${{ github.ref_name || github.sha }} to './target'
        uses: actions/checkout@v3
        with:
          path: target
      - id: git-config-user
        uses: thnetii/.github/actions/git-user-config@main
        with:
          working-directory: target
      - id: create-branch
        uses: thnetii/.github/actions/create-rebase-pr-branch@main
        with:
          branch-name: workflows/w${{ steps.get-workflow-id.outputs.workflow-id }}
          working-directory: target
      - run: |
          git log --graph --abbrev-commit --decorate --author-date-order  --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
        working-directory: target
