name: MSAL Federated Credentials

on:
  workflow_dispatch: {}

jobs:
  msal:
    name: MSAL Authentication
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - name: Authenticate using GitHub action
        uses: thnetii/.github/actions/ms-idp-client-assertion-auth@main
        with:
          tenant-id: ${{ secrets.MSIDP_TENANT_ID }}
          client-id: ${{ secrets.MSIDP_CLIENT_ID }}
